apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: msg-transfer
build:
  artifacts:
  - image: msg-transfer
    jib: {
      type: gradle
    }
  # local:
  #   skipPush: true
deploy:
  kubectl:
    manifests:
    - k8s/msg-transfer.yaml
portForward:
- resourceType: service
  resourceName: msg-transfer
  port: 8080
  localPort: 8080
